FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Install missing modules if volume mount wiped them
RUN test -d node_modules || npm install

CMD ["npm", "run", "dev", "--", "--host"]
